#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# Update formulas.
#
# USAGE:
#    ./tools/formula.sh

OWNER="openrr"
PACKAGES=(
    "urdf-viz" # https://github.com/openrr/urdf-viz
)
DESCRIPTIONS=(
    "URDF visualizer"
)
TESTS=(
    'system "#{bin}/urdf-viz", "--version"'
)

cd "$(cd "$(dirname "$0")" && pwd)"/..

for i in "${!PACKAGES[@]}"; do
    package="${PACKAGES[${i}]}"
    class=$(sed -r 's/(^|-)(\w)/\U\2/g' <<<"${package}")
    set -x
    tag=$(curl -fsSL --retry 3 "https://api.github.com/repos/${OWNER}/${package}/releases/latest" | jq -r '.tag_name')
    mac_url="https://github.com/${OWNER}/${package}/releases/download/${tag}/${package}-x86_64-apple-darwin.tar.gz"
    linux_url="https://github.com/${OWNER}/${package}/releases/download/${tag}/${package}-x86_64-unknown-linux-gnu.tar.gz"
    mac_sha="$(curl -fsSL --retry 3 "${mac_url}" | sha256sum)"
    linux_sha="$(curl -fsSL --retry 3 "${linux_url}" | sha256sum)"
    set +x

    cat >./Formula/"${package}".rb <<EOF
# This file is @generated by $(basename "$0").
# It is not intended for manual editing.
class ${class} < Formula
  desc "${DESCRIPTIONS[${i}]}"
  homepage "https://github.com/${OWNER}/${package}"
  version "${tag#v}"
  license "Apache-2.0"

  on_macos do
    url "${mac_url}"
    sha256 "${mac_sha%  *}"
  end
  on_linux do
    if Hardware::CPU.intel?
      url "${linux_url}"
      sha256 "${linux_sha%  *}"
    end
  end

  def install
    bin.install "${package}"
  end

  test do
    ${TESTS[${i}]}
  end
end
EOF
done
